apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: pytest-calculator
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: pytest-calculator
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
